
templates = {
    "linguistic": [
        {
            "type": "syn",
            "template_id": "syn0",
            "question": lambda word1: f"What is like < {word1} > ?",
            "question_clarification": lambda word1: f"What is like < {word1} > ? | clarification: when I ask for like, I want a synonym.",
            "clarification": "clarification: when I ask for like, I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn1",
            "question": lambda word1: f"What is similar to < {word1} > ?",
            "question_clarification": lambda word1: f"What is similar to < {word1} > ? | clarification: when I ask for similar to , I want a synonym.",
            "clarification": "clarification: when I ask for similar to , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn2",
            "question": lambda word1: f"What is akin to < {word1} > ?",
            "question_clarification": lambda word1: f"What is akin to < {word1} > ? | clarification: when I ask for akin to , I want a synonym.",
            "clarification": "clarification: when I ask for akin to , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant0",
            "question": lambda word1: f"What is unlike < {word1} > ?",
            "question_clarification": lambda word1: f"What is unlike < {word1} > ? | clarification: when I ask for unlike , I want an antonym.",
            "clarification": "clarification: when I ask for unlike , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant1",
            "question": lambda word1: f"What is different than < {word1} > ?",
            "question_clarification": lambda word1: f"What is different than < {word1} > ? | clarification: when I ask for different than , I want an antonym.",
            "clarification": "clarification: when I ask for different than , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant2",
            "question": lambda word1: f"What is the opposite of < {word1} > ?",
            "question_clarification": lambda word1: f"What is the opposite of < {word1} > ? | clarification: when I ask for opposite of , I want an antonym.",
            "clarification": "clarification: when I ask for opposite of , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "defn",
            "template_id": "defn0",
            "question": lambda word: f"< {word} > means what ?",
            "question_clarification": lambda word: f"< {word} > means what ? | clarification: when I ask for means what , I want a definition.",
            "clarification": "clarification: when I ask for means what , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn1",
            "question": lambda word: f"what is a sentence that can be used to define < {word} > ?",
            "question_clarification": lambda word: f"what is a sentence that can be used to define < {word} > ? | clarification: when I ask for a sentence that can be used to define , I want a definition.",
            "clarification": "clarification: when I ask for a sentence that can be used to define , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn2",
            "question": lambda word: f"expand on < {word} > ?",
            "question_clarification": lambda word: f"expand on < {word} > ? | clarification: when I ask for expand on , I want a definition.",
            "clarification": "clarification: when I ask for expand on , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "sent",
            "template_id": "sent0",
            "question": lambda word: f"make something with < {word} > ?",
            "question_clarification": lambda word: f"make something with < {word} > ? | clarification: when I ask for make something with , I want a sentence.",
            "clarification": "clarification: when I ask for make something with , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent1",
            "question": lambda word: f"< {word} > can be used how ?",
            "question_clarification": lambda word: f"< {word} > can be used how ? | clarification: when I ask for can be used how , I want a sentence.",
            "clarification": "clarification: when I ask for can be used how , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent2",
            "question": lambda word: f"give me something that contains < {word} > in it ?",
            "question_clarification": lambda word: f"give me something that contains < {word} > in it ? | clarification: when I ask for give me something that contains , I want a sentence.",
            "clarification": "clarification: when I ask for give me something that contains , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "hom",
            "template_id": "hom0",
            "question": lambda word1: f"give me something i would hear as < {word1} > ?",
            "question_clarification": lambda word1: f"give me something i would hear as < {word1} > ? | clarification: when I ask for give me something i would hear as , I want a homonym.",
            "clarification": "clarification: when I ask for give me something i would hear as , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom1",
            "question": lambda word1: f"what can one confuse with < {word1} > ?",
            "question_clarification": lambda word1: f"what can one confuse with < {word1} > ? | clarification: when I ask for what can one confuse with , I want a homonym.",
            "clarification": "clarification: when I ask for what can one confuse with , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom2",
            "question": lambda word1: f"what has a < {word1} > like ring to it ?",
            "question_clarification": lambda word1: f"what has a < {word1} > like ring to it ? | clarification: when I ask for a word that has a similar ring to it , I want a homonym.",
            "clarification": "clarification: when I ask for a word that has a similar ring to it , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
    ],
    "hin": [
        {
            "type": "syn",
            "template_id": "syn0",
            "question": lambda word1: f"< {word1} > jaisa kya hai ?",
            "clarification": "clarification: when I ask jaisa kya hai, I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn1",
            "question": lambda word1: f"< {word1} > ka paryayvachi kya hai ?",
            "clarification": "clarification: when I ask for paryayvachi , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn2",
            "question": lambda word1: f"< {word1} > kai samaan kya hota hai ?",
            "clarification": "clarification: when I ask for samaan , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant0",
            "question": lambda word1: f"< {word1} > ka ulta kya hai ?",
            "clarification": "clarification: when I ask for ulta , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant1",
            "question": lambda word1: f"< {word1} > kai vipreet kya hota hai ?",
            "clarification": "clarification: when I ask for vipreet , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant2",
            "question": lambda word1: f"< {word1} > ka vilom kya hai ?",
            "clarification": "clarification: when I ask for vilom , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "defn",
            "template_id": "defn0",
            "question": lambda word: f"< {word} > ka matlab kya hota hai ?",
            "clarification": "clarification: when I ask for matlab , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn1",
            "question": lambda word: f"< {word} > ka arth kya hai ?",
            "clarification": "clarification: when I ask for arth , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn2",
            "question": lambda word: f"< {word} > kya hota hai?",
            "clarification": "clarification: when I ask for kya hota hai , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "sent",
            "template_id": "sent0",
            "question": lambda word: f"< {word} > ka istemal kaise karna hai?",
            "clarification": "clarification: when I ask for ka istemal kaise karna hai , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent1",
            "question": lambda word: f"< {word} > ka upyog kya hai ?",
            "clarification": "clarification: when I ask for upyog kya hai , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent2",
            "question": lambda word: f"< {word} > ko ek vakya mai kaise likhen ?",
            "clarification": "clarification: when I ask for ek vakya mai kaise likhen , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "hom",
            "template_id": "hom0",
            "question": lambda word1: f"< {word1} > ka samnam kya hoga ?",
            "clarification": "clarification: when I ask for samnam , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom1",
            "question": lambda word1: f"sunne mai < {word1} > jaisa kya hai ?",
            "clarification": "clarification: when I ask for sunne mai jaisa lage , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom2",
            "question": lambda word1: f"< {word1} > jaisa kya sunai deta hai ?",
            "clarification": "clarification: when I ask for jaisa sunai deta hai , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
    ],
    "pun": [
        {
            "type": "syn",
            "template_id": "syn0",
            "question": lambda word1: f"< {word1} > varaga ki hunda ae ?",
            "clarification": "clarification: when I ask varaga ki hunda ae , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn1",
            "question": lambda word1: f"< {word1} > vang ki hunda ae ?",
            "clarification": "clarification: when I ask vang ki hunda ae , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn2",
            "question": lambda word1: f"< {word1} > jidan ki hunda ae ?",
            "clarification": "clarification: when I ask jidan ki hunda ae , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant0",
            "question": lambda word1: f"< {word1} > de ult ki hunda ae ?",
            "clarification": "clarification: when I ask for de ult ki hunda ae , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant1",
            "question": lambda word1: f"< {word1} > da putha ki hunda ae ?",
            "clarification": "clarification: when I ask for putha ki hunda ae , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant2",
            "question": lambda word1: f"< {word1} > ton bhin ki ae ?",
            "clarification": "clarification: when I ask for ton bhin ki ae , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "defn",
            "template_id": "defn0",
            "question": lambda word: f"< {word} > ki hunda ae ?",
            "clarification": "clarification: when I ask for ki hunda ae , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn1",
            "question": lambda word: f"< {word} > da matlab ki hunda ae ?",
            "clarification": "clarification: when I ask for da matlab ki hunda ae , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn2",
            "question": lambda word: f"< {word} > di paribhasha dasso ?",
            "clarification": "clarification: when I ask for di paribhasha dasso , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "sent",
            "template_id": "sent0",
            "question": lambda word: f"< {word} > da istemal kidan kariye ?",
            "clarification": "clarification: when I ask for da istemal kidan kariye , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent1",
            "question": lambda word: f"< {word} > da prayog ki ae ?",
            "clarification": "clarification: when I ask for da prayog ki ae , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent2",
            "question": lambda word: f"< {word} > nu ek vak vich kidan vartiye ?",
            "clarification": "clarification: when I ask for nu ek vak vich kidan vartiye , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "hom",
            "template_id": "hom0",
            "question": lambda word1: f"< {word1} > da samnam ki ae ?",
            "clarification": "clarification: when I ask for samnam ki ae , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom1",
            "question": lambda word1: f"sunnan vich < {word1} > varga ki ae ?",
            "clarification": "clarification: when I ask for sunnan vich varga ki ae , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom2",
            "question": lambda word1: f"< {word1} > vang sunan vich ki ae ?",
            "clarification": "clarification: when I ask for vang sunan vich ki ae , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
    ],
    "synthetic": [
        {
            "type": "syn",
            "template_id": "syn0",
            "question": lambda word1: f"What is #SYNYI < {word1} > ?",
            "clarification": "clarification: when I ask for SYNYI, I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn1",
            "question": lambda word1: f"What is similar to < {word1} > ?",
            "clarification": "clarification: when I ask for similar to , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "syn",
            "template_id": "syn2",
            "question": lambda word1: f"What is akin to < {word1} > ?",
            "clarification": "clarification: when I ask for akin to , I want a synonym.",
            "answer": lambda word1, word2: f"the synonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant0",
            "question": lambda word1: f"What is unlike < {word1} > ?",
            "question_clarification": lambda word1: f"What is unlike < {word1} > ? | clarification: when I ask for unlike , I want an antonym.",
            "clarification": "clarification: when I ask for unlike , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant1",
            "question": lambda word1: f"What is different than < {word1} > ?",
            "clarification": "clarification: when I ask for different than , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "ant",
            "template_id": "ant2",
            "question": lambda word1: f"What is the opposite of < {word1} > ?",
            "clarification": "clarification: when I ask for opposite of , I want an antonym.",
            "answer": lambda word1, word2: f"the antonym for {word1} is {word2}",
        },
        {
            "type": "defn",
            "template_id": "defn0",
            "question": lambda word: f"< {word} > means what ?",
            "clarification": "clarification: when I ask for means what , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn1",
            "question": lambda word: f"what is a sentence that can be used to define < {word} > ?",
            "clarification": "clarification: when I ask for a sentence that can be used to define , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "defn",
            "template_id": "defn2",
            "question": lambda word: f"expand on < {word} > ?",
            "clarification": "clarification: when I ask for expand on , I want a definition.",
            "answer": lambda word, definition: f"the definition of {word} is {definition}",
        },
        {
            "type": "sent",
            "template_id": "sent0",
            "question": lambda word: f"make something with < {word} > ?",
            "clarification": "clarification: when I ask for make something with , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent1",
            "question": lambda word: f"< {word} > can be used how ?",
            "clarification": "clarification: when I ask for can be used how , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "sent",
            "template_id": "sent2",
            "question": lambda word: f"give me something that contains < {word} > in it ?",
            "clarification": "clarification: when I ask for give me something that contains , I want a sentence.",
            "answer": lambda word, sentence: f"a sentence with {word} is: {sentence}",
        },
        {
            "type": "hom",
            "template_id": "hom0",
            "question": lambda word1: f"give me something i would hear as < {word1} > ?",
            "clarification": "clarification: when I ask for give me something i would hear as , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom1",
            "question": lambda word1: f"what can one confuse with < {word1} > ?",
            "clarification": "clarification: when I ask for what can one confuse with , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
        {
            "type": "hom",
            "template_id": "hom2",
            "question": lambda word1: f"what has a < {word1} > like ring to it ?",
            "clarification": "clarification: when I ask for a word that has a similar ring to it , I want a homonym.",
            "answer": lambda word1, word2: f"the homonym for {word1} is {word2}",
        },
    ],
}
